spring:
    datasource:
        password: ''
        url: jdbc:mysql://localhost:3306/shop2?useUnicode=yes&characterEncoding=UTF-8&useSSl=false
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    thymeleaf:
        cache: false
