#spring:
#    profiles:
#        active: heroku
#    datasource:
#        password: ''
#        url: jdbc:mysql://localhost:3306/shop2?useUnicode=yes&characterEncoding=UTF-8&useSSl=false
#        username: root
#    jpa:
#        hibernate:
#            ddl-auto: none
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5Dialect
#        show-sql: true
#    thymeleaf:
#        cache: false

spring:
    profiles:
        active: heroku



    ################################################
    application:
        name: Shop Demo
    mail:
        host: smtp.gmail.com
        username: yenpham123456987@gmail.com
        password: fycjdznwxpltntdg
        port: 587
        properties.mail.smtp.starttls.enable: true
################################################
server:
    port: 8080
    use-forward-headers: true
