spring:
  datasource:
    url: jdbc:${JAWSDB_URL}
    username: ''
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false
  thymeleaf:
    cache: true
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

